print('hello world')
print('curso senai')
print('phyton')
print('aleatório')
print('aleatório')
print('aleatório')
print('aleatório')
print('aleatório')
print ('aleatório')
print ('aleatório')